package edu.udistrital.plantae.persistencia;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import edu.udistrital.plantae.logicadominio.datosespecimen.Especimen;
import edu.udistrital.plantae.logicadominio.datosespecimen.EspecimenColectorSecundario;
import edu.udistrital.plantae.logicadominio.recoleccion.ColectorSecundario;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ESPECIMEN_COLECTOR_SECUNDARIO.
*/
public class EspecimenColectorSecundarioDao extends AbstractDao<EspecimenColectorSecundario, Long> {

    public static final String TABLENAME = "ESPECIMEN_COLECTOR_SECUNDARIO";

    /**
     * Properties of entity EspecimenColectorSecundario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EspecimenID = new Property(1, Long.class, "especimenID", false, "ESPECIMEN_ID");
        public final static Property ColectorSecundarioID = new Property(2, Long.class, "colectorSecundarioID", false, "COLECTOR_SECUNDARIO_ID");
    };

    private DaoSession daoSession;

    private Query<EspecimenColectorSecundario> colectorSecundario_EspecimenesQuery;
    private Query<EspecimenColectorSecundario> especimen_ColectoresSecundariosQuery;

    public EspecimenColectorSecundarioDao(DaoConfig config) {
        super(config);
    }
    
    public EspecimenColectorSecundarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ESPECIMEN_COLECTOR_SECUNDARIO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ESPECIMEN_ID' INTEGER," + // 1: especimenID
                "'COLECTOR_SECUNDARIO_ID' INTEGER);"); // 2: colectorSecundarioID
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_ESPECIMEN_COLECTOR_SECUNDARIO_ESPECIMEN_ID_COLECTOR_SECUNDARIO_ID ON ESPECIMEN_COLECTOR_SECUNDARIO" +
                " (ESPECIMEN_ID,COLECTOR_SECUNDARIO_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ESPECIMEN_COLECTOR_SECUNDARIO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EspecimenColectorSecundario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long especimenID = entity.getEspecimenID();
        if (especimenID != null) {
            stmt.bindLong(2, especimenID);
        }
 
        Long colectorSecundarioID = entity.getColectorSecundarioID();
        if (colectorSecundarioID != null) {
            stmt.bindLong(3, colectorSecundarioID);
        }
    }

    @Override
    protected void attachEntity(EspecimenColectorSecundario entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public EspecimenColectorSecundario readEntity(Cursor cursor, int offset) {
        EspecimenColectorSecundario entity = new EspecimenColectorSecundario();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EspecimenColectorSecundario entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEspecimenID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setColectorSecundarioID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(EspecimenColectorSecundario entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(EspecimenColectorSecundario entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "especimenes" to-many relationship of ColectorSecundario. */
    public List<EspecimenColectorSecundario> _queryColectorSecundario_Especimenes(Long colectorSecundarioID) {
        synchronized (this) {
            if (colectorSecundario_EspecimenesQuery == null) {
                QueryBuilder<EspecimenColectorSecundario> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ColectorSecundarioID.eq(null));
                colectorSecundario_EspecimenesQuery = queryBuilder.build();
            }
        }
        Query<EspecimenColectorSecundario> query = colectorSecundario_EspecimenesQuery.forCurrentThread();
        query.setParameter(0, colectorSecundarioID);
        return query.list();
    }

    /** Internal query to resolve the "colectoresSecundarios" to-many relationship of Especimen. */
    public List<EspecimenColectorSecundario> _queryEspecimen_ColectoresSecundarios(Long especimenID) {
        synchronized (this) {
            if (especimen_ColectoresSecundariosQuery == null) {
                QueryBuilder<EspecimenColectorSecundario> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.EspecimenID.eq(null));
                especimen_ColectoresSecundariosQuery = queryBuilder.build();
            }
        }
        Query<EspecimenColectorSecundario> query = especimen_ColectoresSecundariosQuery.forCurrentThread();
        query.setParameter(0, especimenID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getColectorSecundarioDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getEspecimenDao().getAllColumns());
            builder.append(" FROM ESPECIMEN_COLECTOR_SECUNDARIO T");
            builder.append(" LEFT JOIN COLECTOR_SECUNDARIO T0 ON T.'COLECTOR_SECUNDARIO_ID'=T0.'_id'");
            builder.append(" LEFT JOIN ESPECIMEN T1 ON T.'ESPECIMEN_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected EspecimenColectorSecundario loadCurrentDeep(Cursor cursor, boolean lock) {
        EspecimenColectorSecundario entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ColectorSecundario colectorSecundario = loadCurrentOther(daoSession.getColectorSecundarioDao(), cursor, offset);
        entity.setColectorSecundario(colectorSecundario);
        offset += daoSession.getColectorSecundarioDao().getAllColumns().length;

        Especimen especimen = loadCurrentOther(daoSession.getEspecimenDao(), cursor, offset);
        entity.setEspecimen(especimen);

        return entity;    
    }

    public EspecimenColectorSecundario loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<EspecimenColectorSecundario> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<EspecimenColectorSecundario> list = new ArrayList<EspecimenColectorSecundario>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<EspecimenColectorSecundario> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<EspecimenColectorSecundario> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
