package edu.udistrital.plantae.persistencia;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import edu.udistrital.plantae.logicadominio.datosespecimen.ColorEspecimen;
import edu.udistrital.plantae.logicadominio.datosespecimen.Raiz;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RAIZ.
*/
public class RaizDao extends AbstractDao<Raiz, Long> {

    public static final String TABLENAME = "RAIZ";

    /**
     * Properties of entity Raiz.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DiametroDeLasRaices = new Property(1, String.class, "diametroDeLasRaices", false, "DIAMETRO_DE_LAS_RAICES");
        public final static Property DiametroEnLaBase = new Property(2, String.class, "diametroEnLaBase", false, "DIAMETRO_EN_LA_BASE");
        public final static Property FormaDeLasEspinas = new Property(3, String.class, "formaDeLasEspinas", false, "FORMA_DE_LAS_ESPINAS");
        public final static Property TamañoDeLasEspinas = new Property(4, String.class, "tamañoDeLasEspinas", false, "TAMAÑO_DE_LAS_ESPINAS");
        public final static Property Descripcion = new Property(5, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property RaizArmada = new Property(6, Boolean.class, "raizArmada", false, "RAIZ_ARMADA");
        public final static Property AlturaDelCono = new Property(7, Long.class, "alturaDelCono", false, "ALTURA_DEL_CONO");
        public final static Property ColorDelConoID = new Property(8, Long.class, "colorDelConoID", false, "COLOR_DEL_CONO_ID");
    };

    private DaoSession daoSession;


    public RaizDao(DaoConfig config) {
        super(config);
    }
    
    public RaizDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'RAIZ' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DIAMETRO_DE_LAS_RAICES' TEXT," + // 1: diametroDeLasRaices
                "'DIAMETRO_EN_LA_BASE' TEXT," + // 2: diametroEnLaBase
                "'FORMA_DE_LAS_ESPINAS' TEXT," + // 3: formaDeLasEspinas
                "'TAMAÑO_DE_LAS_ESPINAS' TEXT," + // 4: tamañoDeLasEspinas
                "'DESCRIPCION' TEXT," + // 5: descripcion
                "'RAIZ_ARMADA' INTEGER," + // 6: raizArmada
                "'ALTURA_DEL_CONO' INTEGER," + // 7: alturaDelCono
                "'COLOR_DEL_CONO_ID' INTEGER);"); // 8: colorDelConoID
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_RAIZ_COLOR_DEL_CONO_ID ON RAIZ" +
                " (COLOR_DEL_CONO_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RAIZ'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Raiz entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String diametroDeLasRaices = entity.getDiametroDeLasRaices();
        if (diametroDeLasRaices != null) {
            stmt.bindString(2, diametroDeLasRaices);
        }
 
        String diametroEnLaBase = entity.getDiametroEnLaBase();
        if (diametroEnLaBase != null) {
            stmt.bindString(3, diametroEnLaBase);
        }
 
        String formaDeLasEspinas = entity.getFormaDeLasEspinas();
        if (formaDeLasEspinas != null) {
            stmt.bindString(4, formaDeLasEspinas);
        }
 
        String tamañoDeLasEspinas = entity.getTamañoDeLasEspinas();
        if (tamañoDeLasEspinas != null) {
            stmt.bindString(5, tamañoDeLasEspinas);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(6, descripcion);
        }
 
        Boolean raizArmada = entity.getRaizArmada();
        if (raizArmada != null) {
            stmt.bindLong(7, raizArmada ? 1l: 0l);
        }
 
        Long alturaDelCono = entity.getAlturaDelCono();
        if (alturaDelCono != null) {
            stmt.bindLong(8, alturaDelCono);
        }

        Long colorDelConoID = entity.getColorDelConoID();
        if (colorDelConoID != null) {
            stmt.bindLong(9, colorDelConoID);
        }
    }

    @Override
    protected void attachEntity(Raiz entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Raiz readEntity(Cursor cursor, int offset) {
        Raiz entity = new Raiz();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Raiz entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDiametroDeLasRaices(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDiametroEnLaBase(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFormaDeLasEspinas(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTamañoDeLasEspinas(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDescripcion(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRaizArmada(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setAlturaDelCono(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setColorDelConoID(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Raiz entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Raiz entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getColorEspecimenDao().getAllColumns());
            builder.append(" FROM RAIZ T");
            builder.append(" LEFT JOIN COLOR_ESPECIMEN T0 ON T.'COLOR_DEL_CONO_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected Raiz loadCurrentDeep(Cursor cursor, boolean lock) {
        Raiz entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ColorEspecimen colorDelCono = loadCurrentOther(daoSession.getColorEspecimenDao(), cursor, offset);
        entity.setColorDelCono(colorDelCono);

        return entity;
    }

    public Raiz loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Raiz> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Raiz> list = new ArrayList<Raiz>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }

    protected List<Raiz> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }


    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Raiz> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }

}
