package edu.udistrital.plantae.persistencia;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;
import edu.udistrital.plantae.logicadominio.autenticacion.Usuario;
import edu.udistrital.plantae.logicadominio.ubicacion.Departamento;
import edu.udistrital.plantae.logicadominio.ubicacion.Municipio;
import edu.udistrital.plantae.logicadominio.ubicacion.Pais;
import edu.udistrital.plantae.logicadominio.ubicacion.Region;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table REGION.
*/
public class RegionDao extends AbstractDao<Region, Long> {

    public static final String TABLENAME = "REGION";

    /**
     * Properties of entity Region.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Pais = new Property(1, String.class, "pais", false, "PAIS");
        public final static Property Departamento = new Property(2, String.class, "departamento", false, "DEPARTAMENTO");
        public final static Property Municipio = new Property(3, String.class, "municipio", false, "MUNICIPIO");
        public final static Property Rango = new Property(4, String.class, "rango", false, "RANGO");
        public final static Property NombreCompleto = new Property(5, String.class, "nombreCompleto", false, "NOMBRE_COMPLETO");
        public final static Property UsuarioId = new Property(6, long.class, "usuarioId", false, "USUARIO_ID");
    };

    private DaoSession daoSession;

    private Query<Region> usuario_RegionesQuery;

    public RegionDao(DaoConfig config) {
        super(config);
    }
    
    public RegionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'REGION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'PAIS' TEXT," + // 1: pais
                "'DEPARTAMENTO' TEXT," + // 2: departamento
                "'MUNICIPIO' TEXT," + // 3: municipio
                "'RANGO' TEXT," + // 4: rango
                "'NOMBRE_COMPLETO' TEXT," + // 5: nombreCompleto
                "'USUARIO_ID' INTEGER NOT NULL );"); // 6: usuarioId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_REGION_PAIS ON REGION" +
                " (PAIS);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_REGION_DEPARTAMENTO ON REGION" +
                " (DEPARTAMENTO);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_REGION_MUNICIPIO ON REGION" +
                " (MUNICIPIO);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_REGION_NOMBRE_COMPLETO ON REGION" +
                " (NOMBRE_COMPLETO);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_REGION_USUARIO_ID ON REGION" +
                " (USUARIO_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'REGION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Region entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String rango = "";
        String nombre = entity.getNombre();
        if (entity instanceof Pais){
            if (nombre != null) {
                stmt.bindString(2, nombre);
                rango = "pais";
            }
        }
        if (entity instanceof Departamento){
            String pais = entity.getRegionPadre().getNombre();
            if (pais != null){
                stmt.bindString(2, pais);
            }
            if (nombre != null) {
                stmt.bindString(3, nombre);
            }
            rango = "departamento";
        }
        if (entity instanceof Municipio){
            String pais = entity.getRegionPadre().getRegionPadre().getNombre();
            if (pais != null){
                stmt.bindString(2, pais);
            }
            String departamento = entity.getRegionPadre().getNombre();
            if (departamento != null) {
                stmt.bindString(3, departamento);
            }
            if (nombre != null) {
                stmt.bindString(4, nombre);
            }
            rango = "municipio";
        }
        stmt.bindString(5, rango);
        /*String pais = entity.getPais();
        if (pais != null) {
            stmt.bindString(2, pais);
        }
 
        String departamento = entity.getDepartamento();
        if (departamento != null) {
            stmt.bindString(3, departamento);
        }
 
        String municipio = entity.getMunicipio();
        if (municipio != null) {
            stmt.bindString(4, municipio);
        }
 
        String rango = entity.getRango();
        if (rango != null) {
            stmt.bindString(5, rango);
        }*/
 
        String nombreCompleto = entity.getNombreCompleto();
        if (nombreCompleto != null) {
            stmt.bindString(6, nombreCompleto);
        }
        stmt.bindLong(7, entity.getUsuarioId());
    }

    @Override
    protected void attachEntity(Region entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Region readEntity(Cursor cursor, int offset) {
        Region entity = null;
        String rango = cursor.getString(offset + 4);
        switch (rango) {
            case "pais":
                entity = new Pais();
                break;
            case "departamento":
                entity = new Departamento();
                break;
            case "municipio":
                entity = new Municipio();
                break;
        }
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Region entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        if (entity instanceof Pais){
            entity.setNombre(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        }
        if (entity instanceof Departamento){
            Region pais = new Pais(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
            entity.setNombre(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
            entity.setRegionPadre(pais);
        }
        if (entity instanceof Municipio){
            Region pais = new Pais(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
            Region departamento = new Departamento(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
            entity.setNombre(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
            departamento.setRegionPadre(pais);
            entity.setRegionPadre(departamento);
        }
        entity.setNombreCompleto(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUsuarioId(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Region entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Region entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }

    /** Internal query to resolve the "regiones" to-many relationship of Usuario. */
    public List<Region> _queryUsuario_Regiones(long usuarioId) {
        synchronized (this) {
            if (usuario_RegionesQuery == null) {
                QueryBuilder<Region> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UsuarioId.eq(null));
                usuario_RegionesQuery = queryBuilder.build();
            }
        }
        Query<Region> query = usuario_RegionesQuery.forCurrentThread();
        query.setParameter(0, usuarioId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUsuarioDao().getAllColumns());
            builder.append(" FROM REGION T");
            builder.append(" LEFT JOIN USUARIO T0 ON T.'USUARIO_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected Region loadCurrentDeep(Cursor cursor, boolean lock) {
        Region entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Usuario usuario = loadCurrentOther(daoSession.getUsuarioDao(), cursor, offset);
         if(usuario != null) {
            entity.setUsuario(usuario);
        }

        return entity;
    }

    public Region loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Region> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Region> list = new ArrayList<Region>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }

    protected List<Region> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }


    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Region> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
    
}
