package edu.udistrital.plantae.persistencia;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;
import edu.udistrital.plantae.logicadominio.autenticacion.Persona;
import edu.udistrital.plantae.logicadominio.recoleccion.ColectorSecundario;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table COLECTOR_SECUNDARIO.
*/
public class ColectorSecundarioDao extends AbstractDao<ColectorSecundario, Long> {

    public static final String TABLENAME = "COLECTOR_SECUNDARIO";

    /**
     * Properties of entity ColectorSecundario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ViajeID = new Property(1, Long.class, "viajeID", false, "VIAJE_ID");
        public final static Property EspecimenID = new Property(2, Long.class, "especimenID", false, "ESPECIMEN_ID");
        public final static Property PersonaID = new Property(3, long.class, "personaID", false, "PERSONA_ID");
    };

    private DaoSession daoSession;

    private Query<ColectorSecundario> viaje_ColectoresSecundariosQuery;
    private Query<ColectorSecundario> especimen_ColectoresSecundariosQuery;

    public ColectorSecundarioDao(DaoConfig config) {
        super(config);
    }
    
    public ColectorSecundarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'COLECTOR_SECUNDARIO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'VIAJE_ID' INTEGER," + // 1: viajeID
                "'ESPECIMEN_ID' INTEGER," + // 2: especimenID
                "'PERSONA_ID' INTEGER NOT NULL );"); // 3: personaID
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_COLECTOR_SECUNDARIO_VIAJE_ID ON COLECTOR_SECUNDARIO" +
                " (VIAJE_ID);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_COLECTOR_SECUNDARIO_ESPECIMEN_ID ON COLECTOR_SECUNDARIO" +
                " (ESPECIMEN_ID);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_COLECTOR_SECUNDARIO_PERSONA_ID ON COLECTOR_SECUNDARIO" +
                " (PERSONA_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'COLECTOR_SECUNDARIO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ColectorSecundario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long viajeID = entity.getViajeID();
        if (viajeID != null) {
            stmt.bindLong(2, viajeID);
        }
 
        Long especimenID = entity.getEspecimenID();
        if (especimenID != null) {
            stmt.bindLong(3, especimenID);
        }
        stmt.bindLong(4, entity.getPersonaID());
    }

    @Override
    protected void attachEntity(ColectorSecundario entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ColectorSecundario readEntity(Cursor cursor, int offset) {
        ColectorSecundario entity = new ColectorSecundario();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ColectorSecundario entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setViajeID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setEspecimenID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setPersonaID(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ColectorSecundario entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ColectorSecundario entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "colectoresSecundarios" to-many relationship of Viaje. */
    public List<ColectorSecundario> _queryViaje_ColectoresSecundarios(Long viajeID) {
        synchronized (this) {
            if (viaje_ColectoresSecundariosQuery == null) {
                QueryBuilder<ColectorSecundario> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ViajeID.eq(null));
                viaje_ColectoresSecundariosQuery = queryBuilder.build();
            }
        }
        Query<ColectorSecundario> query = viaje_ColectoresSecundariosQuery.forCurrentThread();
        query.setParameter(0, viajeID);
        return query.list();
    }

    /** Internal query to resolve the "colectoresSecundarios" to-many relationship of Especimen. */
    public List<ColectorSecundario> _queryEspecimen_ColectoresSecundarios(Long especimenID) {
        synchronized (this) {
            if (especimen_ColectoresSecundariosQuery == null) {
                QueryBuilder<ColectorSecundario> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.EspecimenID.eq(null));
                especimen_ColectoresSecundariosQuery = queryBuilder.build();
            }
        }
        Query<ColectorSecundario> query = especimen_ColectoresSecundariosQuery.forCurrentThread();
        query.setParameter(0, especimenID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPersonaDao().getAllColumns());
            builder.append(" FROM COLECTOR_SECUNDARIO T");
            builder.append(" LEFT JOIN PERSONA T0 ON T.'PERSONA_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ColectorSecundario loadCurrentDeep(Cursor cursor, boolean lock) {
        ColectorSecundario entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Persona persona = loadCurrentOther(daoSession.getPersonaDao(), cursor, offset);
         if(persona != null) {
            entity.setPersona(persona);
        }

        return entity;    
    }

    public ColectorSecundario loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ColectorSecundario> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ColectorSecundario> list = new ArrayList<ColectorSecundario>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ColectorSecundario> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ColectorSecundario> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
