package edu.udistrital.plantae.persistencia;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import edu.udistrital.plantae.logicadominio.autenticacion.Persona;
import edu.udistrital.plantae.logicadominio.autenticacion.Usuario;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PERSONA.
*/
public class PersonaDao extends AbstractDao<Persona, Long> {

    public static final String TABLENAME = "PERSONA";

    /**
     * Properties of entity Persona.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombres = new Property(1, String.class, "nombres", false, "NOMBRES");
        public final static Property Apellidos = new Property(2, String.class, "apellidos", false, "APELLIDOS");
        public final static Property Direccion = new Property(3, String.class, "direccion", false, "DIRECCION");
        public final static Property Telefono = new Property(4, String.class, "telefono", false, "TELEFONO");
        public final static Property Institucion = new Property(5, String.class, "institucion", false, "INSTITUCION");
        public final static Property UsuarioID = new Property(6, Long.class, "usuarioID", false, "USUARIO_ID");
    };

    private DaoSession daoSession;


    public PersonaDao(DaoConfig config) {
        super(config);
    }
    
    public PersonaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PERSONA' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NOMBRES' TEXT," + // 1: nombres
                "'APELLIDOS' TEXT," + // 2: apellidos
                "'DIRECCION' TEXT," + // 3: direccion
                "'TELEFONO' TEXT," + // 4: telefono
                "'INSTITUCION' TEXT," + // 5: institucion
                "'USUARIO_ID' INTEGER);"); // 6: usuarioID
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_PERSONA_NOMBRES ON PERSONA" +
                " (NOMBRES);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_PERSONA_APELLIDOS ON PERSONA" +
                " (APELLIDOS);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_PERSONA_USUARIO_ID ON PERSONA" +
                " (USUARIO_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PERSONA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Persona entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nombres = entity.getNombres();
        if (nombres != null) {
            stmt.bindString(2, nombres);
        }
 
        String apellidos = entity.getApellidos();
        if (apellidos != null) {
            stmt.bindString(3, apellidos);
        }
 
        String direccion = entity.getDireccion();
        if (direccion != null) {
            stmt.bindString(4, direccion);
        }
 
        String telefono = entity.getTelefono();
        if (telefono != null) {
            stmt.bindString(5, telefono);
        }
 
        String institucion = entity.getInstitucion();
        if (institucion != null) {
            stmt.bindString(6, institucion);
        }
 
        Long usuarioID = entity.getUsuarioID();
        if (usuarioID != null) {
            stmt.bindLong(7, usuarioID);
        }
    }

    @Override
    protected void attachEntity(Persona entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Persona readEntity(Cursor cursor, int offset) {
        Persona entity = new Persona();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Persona entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombres(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setApellidos(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDireccion(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTelefono(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setInstitucion(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUsuarioID(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Persona entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Persona entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUsuarioDao().getAllColumns());
            builder.append(" FROM PERSONA T");
            builder.append(" LEFT JOIN USUARIO T0 ON T.'USUARIO_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Persona loadCurrentDeep(Cursor cursor, boolean lock) {
        Persona entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Usuario usuario = loadCurrentOther(daoSession.getUsuarioDao(), cursor, offset);
        entity.setUsuario(usuario);

        return entity;    
    }

    public Persona loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Persona> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Persona> list = new ArrayList<Persona>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Persona> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Persona> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
