package edu.udistrital.plantae.persistencia;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import edu.udistrital.plantae.logicadominio.taxonomia.EpitetoEspecifico;
import edu.udistrital.plantae.logicadominio.taxonomia.Familia;
import edu.udistrital.plantae.logicadominio.taxonomia.Genero;
import edu.udistrital.plantae.logicadominio.taxonomia.Taxon;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TAXON.
*/
public class TaxonDao extends AbstractDao<Taxon, Long> {

    public static final String TABLENAME = "TAXON";

    /**
     * Properties of entity Taxon.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Familia = new Property(1, String.class, "familia", false, "FAMILIA");
        public final static Property Genero = new Property(2, String.class, "genero", false, "GENERO");
        public final static Property Especie = new Property(3, String.class, "especie", false, "ESPECIE");
        public final static Property Autor = new Property(4, String.class, "autor", false, "AUTOR");
        public final static Property Rango = new Property(5, String.class, "rango", false, "RANGO");
        public final static Property NombreCientifico = new Property(6, String.class, "nombreCientifico", false, "NOMBRE_CIENTIFICO");
    };

    private DaoSession daoSession;


    public TaxonDao(DaoConfig config) {
        super(config);
    }
    
    public TaxonDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TAXON' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'FAMILIA' TEXT," + // 1: familia
                "'GENERO' TEXT," + // 2: genero
                "'ESPECIE' TEXT," + // 3: especie
                "'AUTOR' TEXT," + // 4: autor
                "'RANGO' TEXT," + // 5: rango
                "'NOMBRE_CIENTIFICO' TEXT);"); // 6: nombreCientifico
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_TAXON_FAMILIA ON TAXON" +
                " (FAMILIA);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_TAXON_GENERO ON TAXON" +
                " (GENERO);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_TAXON_ESPECIE ON TAXON" +
                " (ESPECIE);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_TAXON_RANGO ON TAXON" +
                " (RANGO);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_TAXON_NOMBRE_CIENTIFICO ON TAXON" +
                " (NOMBRE_CIENTIFICO);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TAXON'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Taxon entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String nombre = entity.getNombre();
        String rango = null;
        if (entity instanceof Familia){
            if (nombre != null) {
                stmt.bindString(2, nombre);
            }
            rango = "familia";
        }else if (entity instanceof Genero){
            String familia = entity.getTaxonPadre().getNombre();
            if (familia != null) {
                stmt.bindString(2, familia);
            }
            if (nombre != null) {
                stmt.bindString(3, nombre);
            }
            rango = "genero";
        }else if (entity instanceof EpitetoEspecifico){
            String familia = entity.getTaxonPadre().getTaxonPadre().getNombre();
            if (familia != null) {
                stmt.bindString(2, familia);
            }
            String genero = entity.getTaxonPadre().getNombre();
            if (genero != null) {
                stmt.bindString(3, genero);
            }
            if (nombre != null) {
                stmt.bindString(4, nombre);
            }
            rango = "epitetoespecifico";
        }
        /*String familia = entity.getFamilia();
        if (familia != null) {
            stmt.bindString(2, familia);
        }
 
        String genero = entity.getGenero();
        if (genero != null) {
            stmt.bindString(3, genero);
        }
 
        String especie = entity.getEspecie();
        if (especie != null) {
            stmt.bindString(4, especie);
        }*/
 
        String autor = entity.getAutor();
        if (autor != null) {
            stmt.bindString(5, autor);
        }
 
        /*String rango = entity.getRango();*/
        if (rango != null) {
            stmt.bindString(6, rango);
        }
 
        String nombreCientifico = entity.getNombreCientifico();
        if (nombreCientifico != null) {
            stmt.bindString(7, nombreCientifico);
        }
    }

    @Override
    protected void attachEntity(Taxon entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Taxon readEntity(Cursor cursor, int offset) {
        Taxon entity = null;
        String rango = cursor.getString(offset + 5);
        if (rango.equals("familia")){
        	entity = new Familia();
        }else if (rango.equals("genero")){
        	entity = new Genero();
        }else if (rango.equals("epitetoespecifico")){
        	entity = new EpitetoEspecifico();
        }
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Taxon entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        if (entity instanceof Familia){
            entity.setNombre(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        }else if (entity instanceof Genero){
            entity.setNombre(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        }else if (entity instanceof EpitetoEspecifico){
            entity.setNombre(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        }
        /*entity.setFamilia(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGenero(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEspecie(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));*/
        entity.setAutor(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        /*entity.setRango(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));*/
        entity.setNombreCientifico(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Taxon entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Taxon entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
